# Generated by Django 4.0.4 on 2022-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_finchtoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='finchtoys',
            field=models.ManyToManyField(to='main_app.finchtoy'),
        ),
    ]
